version: '3.7'

services:
  client:
    container_name: client
    init: true
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    command: yarn serve
    volumes:
      - .:/app:${CONSISTENCY:-cached}
      - /app/node_modules
    ports:
      - 8080:8080
      - 8081:8081
