FROM node:10-alpine

ENV \
  APP_DIR="/app" \
  ENTRYKIT_VERSION="0.4.0"

WORKDIR ${APP_DIR}

# Introduce entrykit
RUN set -x && \
  wget https://github.com/progrium/entrykit/releases/download/v${ENTRYKIT_VERSION}/entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
  && tar -xvzf entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
  && rm entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
  && mv entrykit /bin/entrykit \
  && chmod +x /bin/entrykit \
  && entrykit --symlink

ENTRYPOINT [ \
  "prehook", "node -v", "--", \
  "prehook", "yarn install", "--" \
  ]
